name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install coverage tool
      run: sudo apt-get install -y gcovr

    - name: build for test sender
      run: g++ -DUNIT_TEST -Wall -Wextra -fprofile-arcs -ftest-coverage -o sender_test Sender_C/*.c* 
      
    - name: run
      run: ./sender_test
  
    - name: build for test receiver
      run: g++ -DUNIT_TEST -Wall -Wextra -fprofile-arcs -ftest-coverage -o receiver_test Receiver_C/*.c* 
      
    - name: run
      run: ./receiver_test

    - name: collect coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./*.html
        retention-days: 1
        
    - name: build for production sender
      run: g++ -Wall -Wextra -o sender Sender_C/*.c*
    
    - name: build for production receiver
      run: g++ -Wall -Wextra -o receiver Receiver_C/*.c* 
      
    - name: production code run
      run: ./sender | ./receiver
