name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install coverage tool
      run: sudo apt-get install -y gcovr

    - name: build for test sender
      run: g++ -DUNIT_TEST -Wall -Wextra -fprofile-arcs -ftest-coverage -o sender Sender_C/*.c* 
      
    - name: sender test
      run: ./sender
      
       - name: Software build for Testing
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o receiver Receiver_C/Receiver.c 
      
    - name: receiver test
      run: ./receiver

    - name: collect coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./*.html
        retention-days: 1
